# Generated by Django 2.2.6 on 2019-11-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
