# Generated by Django 2.2.6 on 2019-11-25 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelogs',
            name='user_log_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
